name: Continuous Integration BE

on:
  push:
    branches:
      - main
      - feature/*
    paths:
      - backendend/**
      - .github/workflows/**

jobs:
  backend-build:
    name: Backend Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: backend/node_modules
          key: be-node-${{ hashFiles('backend/package-lock.json') }}

      - name: install Dependencies
        run: |
          cd backend && npm i

      - name: Compile code
        run: npm build
